name: Publish Extension

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag to publish"
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Zed
        uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: catppuccin-blur
          push-to: jenslys/extensions
          tag-name: ${{ inputs.tag_name }}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
