name: Sync Theme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [catppuccin-update]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync theme
        run: python sync_theme.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.COMMITTER_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync theme"
          title: "chore: sync theme"
          body: |
            Automated theme sync with latest Catppuccin theme.

            - Synced with latest Catppuccin theme
            - Applied blur customizations
            - Updated all variants including Espresso
          branch: chore/theme-sync
          delete-branch: true
          labels: |
            theme
            automated pr
          add-paths: |
            themes/catppuccin-blur.json
